export const CONTENT_INTELLIGENCE_VERSION = 'content-intelligence-v1';

export const CONTENT_CONFIG = {
  REFRESH_FIRST: true,
  NEW_URL_DEFAULT: false,
  PROGRAMMATIC_SPAM_GUARD: true,
  ACCESS_TRADE_SHOPEE_CONTENT: 'PASS',
  DIRECT_SHOPEE_STATUS: 'DISABLED_NO_CREDENTIALS',
  DIRECT_SHOPEE_API_CALLS: 0,
  LIVE_AI_PROBE: 'NOT_RUN',
  SHADOW_CONTENT_IN_SITEMAP: 0,
  PRODUCTION_EXPERIMENT_TRAFFIC: 0,
  ACTIVE_PRODUCTION_EXPERIMENTS: 0,
  FAKE_SCARCITY_EFFECT: 0,
  AI_CONTENT_FACT_MUTATION_EFFECT: 0,
  FAKE_STRUCTURED_RATING_EFFECT: 0,
  DUPLICATE_CONTENT_PLAN_EFFECT: 0,
  UNCHANGED_CONTENT_REFRESH_EFFECT: 0,
  CONTENT_POLICY_OVERRIDE_EFFECT: 0,
  CONTENT_OPPORTUNITY_SCORE_MUTATION_EFFECT: 0,
  CONTENT_DEAL_SCORE_MUTATION_EFFECT: 0,
  CONTENT_MONEY_ROUTE_OVERRIDE_EFFECT: 0
};
