import type { Product } from './types';


/**
 * Normalize product for public display.
 * - Avoids throwing on missing fields
 * - Computes discountPercent from price/salePrice
 * - Marks missing image and provides placeholder
 */
export function normalizeProductForPublic(p: Partial<Product>): Product {
  const price = typeof p.price === 'number' ? p.price : undefined;
  const salePrice = typeof p.salePrice === 'number' ? p.salePrice : undefined;
  const imageUrl = p.imageUrl && typeof p.imageUrl === 'string' && p.imageUrl.length > 5 ? p.imageUrl : undefined;

  const normalized: Product = {
    id: String(p.id || '') || '',
    title: p.title || 'Sản phẩm chưa có tiêu đề',
    slug: p.slug || (p.title ? String(p.title).toLowerCase().replace(/[^a-z0-9]+/g, '-') : '') || '',
    description: p.description || undefined,
    kind: p.kind || 'unknown',
    platform: p.platform || 'website',
    source: p.source || 'manual',
    originalUrl: p.originalUrl || undefined,
    canonicalProductUrl: p.canonicalProductUrl || p.originalUrl || undefined,
    canonicalUrlSource: p.canonicalUrlSource,
    canonicalUrlProvider: p.canonicalUrlProvider,
    canonicalUrlSourceEndpoint: p.canonicalUrlSourceEndpoint,
    canonicalUrlSourceField: p.canonicalUrlSourceField,
    canonicalUrlFetchedAt: p.canonicalUrlFetchedAt,
    canonicalUrlVerifiedAt: p.canonicalUrlVerifiedAt,
    canonicalUrlStatus: p.canonicalUrlStatus,
    affiliateUrl: p.affiliateUrl || undefined,
    affiliateUrlSource: p.affiliateUrlSource,
    affiliateUrlProvider: p.affiliateUrlProvider,
    affiliateUrlSourceEndpoint: p.affiliateUrlSourceEndpoint,
    affiliateUrlSourceField: p.affiliateUrlSourceField,
    affiliateUrlCampaignId: p.affiliateUrlCampaignId,
    affiliateUrlFetchedAt: p.affiliateUrlFetchedAt,
    affiliateUrlVerifiedAt: p.affiliateUrlVerifiedAt,
    affiliateUrlStatus: p.affiliateUrlStatus,
    quarantinedAffiliateUrl: p.quarantinedAffiliateUrl,
    deepLinkSupported: p.deepLinkSupported,
    affiliateLinkReason: p.affiliateLinkReason,
    imageUrl,
    gallery: Array.isArray(p.gallery) ? p.gallery : [],
    price,
    salePrice,
    currency: 'VND',
    priceNote: p.priceNote || undefined,
    category: p.category || undefined,
    tags: Array.isArray(p.tags) ? p.tags : [],
    benefits: Array.isArray(p.benefits) ? p.benefits : [],
    painPoints: Array.isArray(p.painPoints) ? p.painPoints : [],
    targetAudience: Array.isArray(p.targetAudience) ? p.targetAudience : [],
    warnings: Array.isArray(p.warnings) ? p.warnings : [],
    contentAngles: Array.isArray(p.contentAngles) ? p.contentAngles : [],
    complianceNotes: Array.isArray(p.complianceNotes) ? p.complianceNotes : [],
    affiliateSource: p.affiliateSource || undefined,
    campaignName: p.campaignName || undefined,
    commissionNote: p.commissionNote || undefined,
    affiliateDisclosure: p.affiliateDisclosure || undefined,
    score: typeof p.score === 'number' ? p.score : undefined,
    scoreLabel: p.scoreLabel,
    scoreReasons: Array.isArray(p.scoreReasons) ? p.scoreReasons : undefined,
    scoreWarnings: Array.isArray(p.scoreWarnings) ? p.scoreWarnings : undefined,
    riskLevel: p.riskLevel || 'unknown',
    status: p.status || 'needs_review',
    externalId: p.externalId,
    rawSourceType: p.rawSourceType,
    linkHealthStatus: p.linkHealthStatus,
    linkLastCheckedAt: p.linkLastCheckedAt,
    linkFailureCount: p.linkFailureCount || 0,
    productUrlHttpStatus: p.productUrlHttpStatus,
    productUrlFinalUrl: p.productUrlFinalUrl,
    productUrlFinalDomain: p.productUrlFinalDomain,
    productUrlHealthReason: p.productUrlHealthReason,
    productUrlErrorCode: p.productUrlErrorCode,
    productUrlTimedOut: p.productUrlTimedOut,
    imageHealthStatus: p.imageHealthStatus,
    imageUrlHttpStatus: p.imageUrlHttpStatus,
    imageUrlFinalUrl: p.imageUrlFinalUrl,
    imageUrlHealthReason: p.imageUrlHealthReason,
    archivedReason: p.archivedReason,
    unpublishedReason: p.unpublishedReason,
    contentPackageStatus: p.contentPackageStatus || 'none',
    complianceStatus: p.complianceStatus || 'safe',
    complianceIssues: Array.isArray(p.complianceIssues) ? p.complianceIssues : [],
    generatedContent: p.generatedContent,
    dataCompleteness: computeDataCompleteness(p),
    affiliateHealthStatus: p.affiliateHealthStatus,
    affiliateLastCheckedAt: p.affiliateLastCheckedAt,
    affiliateLinkErrors: p.affiliateLinkErrors,
    affiliateUrlHttpStatus: p.affiliateUrlHttpStatus,
    affiliateUrlFinalUrl: p.affiliateUrlFinalUrl,
    affiliateUrlFinalDomain: p.affiliateUrlFinalDomain,
    affiliateUrlHealthReason: p.affiliateUrlHealthReason,
    affiliateUrlErrorCode: p.affiliateUrlErrorCode,
    affiliateUrlTimedOut: p.affiliateUrlTimedOut,
    imageLastCheckedAt: p.imageLastCheckedAt,
    imageValidationState: p.imageValidationState,
    imageWidth: p.imageWidth,
    imageHeight: p.imageHeight,
    imageDimensionsVerified: p.imageDimensionsVerified,
    sourceHealthCooldownUntil: p.sourceHealthCooldownUntil,
    sourceHealthReason: p.sourceHealthReason,
    sourceHealthSkipUntil: p.sourceHealthSkipUntil,
    sourceId: p.sourceId,
    contentHash: p.contentHash,
    sourceHash: p.sourceHash,
    verifiedSource: p.verifiedSource,
    sourceVerified: p.sourceVerified,
    autoPublishEligible: p.autoPublishEligible,
    publicDecision: p.publicDecision,
    publicHidden: p.publicHidden,
    publicBlocked: p.publicBlocked,
    publicBlockReason: p.publicBlockReason,
    publicBlockReasons: Array.isArray(p.publicBlockReasons) ? p.publicBlockReasons : undefined,
    autoPublished: p.autoPublished,
    needsVerification: p.needsVerification,
    qualityScore: p.qualityScore,
    qualityBand: p.qualityBand,
    opportunityScore: p.opportunityScore,
    opportunityBand: p.opportunityBand,
    scoreVersion: p.scoreVersion,
    scoreCalculatedAt: p.scoreCalculatedAt,
    scoreBreakdown: p.scoreBreakdown,
    dealScore: p.dealScore,
    dealBand: p.dealBand,
    dealReasons: Array.isArray(p.dealReasons) ? p.dealReasons : undefined,
    dealConfidence: p.dealConfidence,
    priceLastChangedAt: p.priceLastChangedAt,
    lastSeenAt: p.lastSeenAt,
    availability: p.availability,
    duplicateGroupId: p.duplicateGroupId,
    duplicateConfidence: p.duplicateConfidence,
    contentWorkflowStatus: p.contentWorkflowStatus,
    lastEditorialCheckAt: p.lastEditorialCheckAt,
    analyticsSummary: p.analyticsSummary,
    dataIssues: Array.isArray(p.dataIssues) ? p.dataIssues : undefined,
    recommendedActions: Array.isArray(p.recommendedActions) ? p.recommendedActions : undefined,
    publishedAt: p.publishedAt,
    productHealthStatus: p.productHealthStatus,
    imageContentType: p.imageContentType,
    brand: p.brand,
    sku: p.sku,
    gtin: p.gtin,
    mpn: p.mpn,
    specifications: p.specifications,
    reviewContent: p.reviewContent,
    reviewQuality: p.reviewQuality,
    eligibility: p.eligibility,
    schemaVersion: p.schemaVersion,
    recordType: p.recordType,
    lifecycleState: p.lifecycleState,
    lifecycleVersion: p.lifecycleVersion,
    lifecycleUpdatedAt: p.lifecycleUpdatedAt,
    evidenceCoverage: p.evidenceCoverage,
    confidences: p.confidences,
    priceTruthState: p.priceTruthState,
    priceObservedAt: p.priceObservedAt,
    duplicateStatus: p.duplicateStatus,
    claimValidationStatus: p.claimValidationStatus,
    lastReprocessOperationId: p.lastReprocessOperationId,
    lastReprocessedAt: p.lastReprocessedAt,
    createdAt: p.createdAt || new Date().toISOString(),
    updatedAt: p.updatedAt || new Date().toISOString(),
  };

  return normalized;
}

function computeDataCompleteness(p: Partial<Product>): number {
  let score = 50; // baseline
  if (p.title) score += 10;
  if (p.description) score += 10;
  if (p.imageUrl) score += 15;
  if (p.price || p.salePrice) score += 10;
  if (p.affiliateUrl || p.originalUrl) score += 5;
  if (Array.isArray(p.benefits) && p.benefits.length > 0) score += 5;
  return Math.max(0, Math.min(100, score));
}
