export const PRODUCT_INTELLIGENCE_CONFIG = {
  versions: {
    quality: 'quality-v1',
    opportunity: 'opportunity-v1',
    deal: 'deal-v1',
    duplicate: 'duplicate-v1',
  },
  limits: {
    publicPageSize: 50,
    adminPageSize: 50,
    csvBytes: 2 * 1024 * 1024,
    csvRows: 1_000,
    csvPreviewRows: 100,
    batchProducts: 100,
    comparisonProducts: 4,
    savedViews: 100,
    collectionRecords: 20_000,
    outboundEvents: 50_000,
    priceSnapshotsPerProduct: 730,
    alerts: 5_000,
  },
  freshness: {
    productDays: 14,
    priceDays: 7,
    editorialDays: 30,
    linkDays: 7,
  },
  retention: {
    outboundEventDays: 90,
    priceHistoryDays: 730,
    growthDailyDays: 730,
    resolvedAlertDays: 90,
  },
  cooldown: {
    alertHours: 24,
    recommendationHours: 24,
    priceCheckpointHours: 24,
  },
  thresholds: {
    qualityGood: 85,
    qualityFair: 70,
    qualityNeedsData: 50,
    opportunityPriority: 80,
    opportunityRecommended: 65,
    opportunityConsider: 45,
    dealFeatured: 80,
    dealConsider: 65,
    dealNormal: 45,
    duplicateHigh: 0.9,
    duplicateMedium: 0.68,
    unusualOriginalPriceRatio: 3,
    strongPriceMovementPercent: 20,
  },
  weights: {
    quality: {
      identity: 18,
      commerce: 22,
      media: 10,
      classification: 10,
      specifications: 10,
      provenance: 12,
      health: 12,
      freshness: 6,
    },
    opportunity: {
      quality: 30,
      deal: 25,
      freshness: 10,
      contentReadiness: 15,
      provenance: 10,
      analytics: 5,
      risk: 5,
    },
    deal: {
      discount: 30,
      history: 20,
      freshness: 15,
      health: 15,
      provenance: 10,
      quality: 10,
    },
  },
} as const;

export type ProductIntelligenceConfig = typeof PRODUCT_INTELLIGENCE_CONFIG;
